// Code generated by go generate; DO NOT EDIT.
package runtimes

var OfficialRuntimes = map[string]Runtime{
	"lamp": {
		Name: "lamp",
		Images: map[string]Image{
			"apache": {
				FullyQualifiedName: "ghcr.io/sinux-l5d/studentbox/lamp.apache",
				ShortName:          "apache",
				Mounts: map[string]string{
					"html": "/var/www/html",
				},
			},
			"mysql": {
				FullyQualifiedName: "ghcr.io/sinux-l5d/studentbox/lamp.mysql",
				ShortName:          "mysql",
				Mounts: map[string]string{
					"db": "/var/lib/mysql",
				},
			},
			"php": {
				FullyQualifiedName: "ghcr.io/sinux-l5d/studentbox/lamp.php",
				ShortName:          "php",
				Mounts: map[string]string{
					"html": "/var/www/html",
				},
			},
		},
	},
}
